
include:
  - project: 'ORIS/orchestrator'
    file: '/NPM-Package.gitlab-ci.yml'
  - project: 'ORIS/orchestrator'
    file: '/jobs/Deploy.gitlab-ci.yml'

stages:
  - install
  - build
  - test
  - publish
  - deploy
  - clean

variables:
  COMPLIANCE: 'S2'
  NEEDS_PAM: 'false'
  # No tests exist yet
  NEEDS_NPM_TEST: 'false'
  # Temp for quick CI iteration
  SAST_DISABLED: 'true'
  DEPENDENCY_SCANNING_DISABLED: 'true'
  CODE_QUALITY_DISABLED: 'true'

# @ORIS/ui needs to build and deploy a styleguide to the dev server upon release.
# We replace the packaging job with the build process
Build Styleguide:
  image: $NODE_IMAGE
  cache:
    key: "$CI_COMMIT_REF_SLUG-node_modules"
    paths:
      - node_modules
    policy: pull
  stage: build # Shift up onto build stage instead
  rules:
    - if: $CI_MERGE_REQUEST_IID
      variables:
        APP_NAME: "$CI_PROJECT_NAME-$CI_MERGE_REQUEST_IID"
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        APP_NAME: $CI_PROJECT_NAME
    - if: '$CI_COMMIT_TAG && $PUBLISHES_NPM_PACKAGE == "true"'
      variables:
        APP_NAME: $CI_PROJECT_NAME
  needs:
    - NPM Install
  script:
    - PUBLIC_URL=/${APP_NAME}
    - echo -e "\nPUBLIC_URL=\"/${APP_NAME}\"" >> $CI_PROJECT_DIR/.env
    - echo -e "\nBUILD_TAG=\"${CI_COMMIT_REF_SLUG}/${CI_COMMIT_SHORT_SHA}\"" >> $CI_PROJECT_DIR/.env
    - echo ARTIFACTS_JOB_ID="${CI_JOB_ID}" >> $CI_PROJECT_DIR/ci.env
    - |
      if [[ $DRY_RUN == 'true' ]]; then
        echo "DRY RUN: npm run build:styleguide";
        exit 0;
      fi
    - npm run build:styleguide
  artifacts:
    paths:
      - styleguide/
    reports:
      dotenv: ci.env

# TODO: APP_NAME for deploy jobs *should* be refactored
# to deploy to different paths based on UI version.

# Current deployment process assumes we deploy a copy of the styleguide
# (if packaging is successful) to dev *and* test on master.

# Change needs for deploy jobs (we don't have a Package job here)
.deploy:
  needs:
    - Build Styleguide

