
include:
  - project: 'ORIS/orchestrator'
    file: '/NPM-Package.gitlab-ci.yml'
  - project: 'ORIS/orchestrator'
    file: '/jobs/Deploy.gitlab-ci.yml'

stages:
  - install
  - build
  - test
  - publish
  - deploy
  - clean

variables:
  COMPLIANCE: 'S2'
  # We haven't written any test automation (yet)
  NEEDS_NPM_TEST: 'false'
  # This project will deploy a styleguide as an internal tool for devs
  DEPLOY_TO_STAGING: 'false'
  NEEDS_PAM: 'false'
  # Temp for quick CI iteration
  SAST_DISABLED: 'true'
  DEPENDENCY_SCANNING_DISABLED: 'true'
  CODE_QUALITY_DISABLED: 'true'

# @ORIS/ui needs to build and deploy a styleguide to the dev server upon release.
# This also doubles as our packaging job for deployments.
Build Styleguide:
  image: $NODE_IMAGE
  cache:
    key: "$CI_COMMIT_REF_SLUG-node_modules"
    paths:
      - node_modules
    policy: pull
  stage: build # Shift up onto build stage instead
  rules:
    - if: $CI_MERGE_REQUEST_IID
      variables:
        APP_NAME: "$CI_PROJECT_NAME-$CI_MERGE_REQUEST_IID"
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        APP_NAME: $CI_PROJECT_NAME
    - if: '$CI_COMMIT_TAG && $PUBLISHES_NPM_PACKAGE == "true"'
      variables:
        APP_NAME: $CI_PROJECT_NAME
  needs:
    - NPM Install
  script:
    - echo -e "\nBUILD_TAG=\"${CI_COMMIT_REF_SLUG}/${CI_COMMIT_SHORT_SHA}\"" >> $CI_PROJECT_DIR/.env
    - echo ARTIFACTS_JOB_ID="${CI_JOB_ID}" >> $CI_PROJECT_DIR/ci.env
    - npm run build:styleguide
  artifacts:
    paths:
      - styleguide/
      - .htaccess
    reports:
      dotenv: ci.env

# Reconfigure all deployment jobs to be dependent on the styleguide and publish jobs.
# Note that the styleguide job exposes the required artifact ID through ci.env
.deploy:
  needs:
    - NPM Publish
    - Build Styleguide
