
# Add Code Quality reporting automatically (built into Gitlab)
#include:
#  - template: Code-Quality.gitlab-ci.yml
#  - template: Dependency-Scanning.gitlab-ci.yml
#  - template: SAST.gitlab-ci.yml

# Local paths that are cached between jobs. Each job runs in
# a separate EC2 instance, these cached files are stored in
# an S3 bucket and copied to each job instance.
cache:
  key: "$CI_COMMIT_REF_SLUG" # Each branch has a separate cache
  paths:
    # Paths added as part of the install stage
    - vendor
    - node_modules

stages:
  - install
  - build
  - deploy

# Hidden base job for PHP work
.php_job:
  # Build that our servers use
  image: php:7.2-alpine

# Hidden base job for Node work
.node_job:
  image: node:15.4

Run Composer Install:
  extends: .php_job
  stage: install
  script:
    - apk update
    - apk add --no-cache git curl
    # Download and run composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-interaction --no-scripts --no-suggest --no-plugins --optimize-autoloader
    # For production, we'd add: --no-dev, but we need it for now to run phpunit and friends.

Run NPM Install:
  extends: .node_job
  stage: install
  script:
    - npm install

Build React App:
  extends: .node_job
  stage: build
  dependencies:
    - install
    
Deploy App:
  extends: .php_job
  dependencies:
    - build
  only:
    - master
  script:
    - |
      curl
        --data "JOB_ID=$CI_JOB_ID" \
        --data "PROJECT_ID=$CI_PROJECT_ID" \
        --data "PROJECT_NAME=$CI_PROJECT_NAME" \
        --data "COMMIT_REF=$CI_COMMIT_REF_NAME" \
        --data "COMMIT_BRANCH=$CI_COMMIT_BRANCH" \
        "https://orapps.osu.edu/orchestrator/artifact"
        
